
[theme]
primaryColor="#8EDC69"
backgroundColor="#157896"
secondaryBackgroundColor="#09313f"
textColor="#ffffff"

[server]
maxUploadSize = 2000

[browser]
gatherUsageStats = false

[client]
toolbarMode = "auto"

